// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDND25OUD0xZ0Vfhxad2m1LH0h8bUvlug',
    appId: '1:961015937007:web:fae26c9c911d036e21e81a',
    messagingSenderId: '961015937007',
    projectId: 'ai-chat-bot-d574b',
    authDomain: 'ai-chat-bot-d574b.firebaseapp.com',
    storageBucket: 'ai-chat-bot-d574b.firebasestorage.app',
    measurementId: 'G-3REK96EVZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD38yOIbUGNPVDhrDrXR3UclmvoKFVVT8U',
    appId: '1:961015937007:android:2785ae7bd808bab621e81a',
    messagingSenderId: '961015937007',
    projectId: 'ai-chat-bot-d574b',
    storageBucket: 'ai-chat-bot-d574b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRZxwOzpmKx54FxdQBFgobymytAUXmzjA',
    appId: '1:961015937007:ios:69c50ff7e7152b9a21e81a',
    messagingSenderId: '961015937007',
    projectId: 'ai-chat-bot-d574b',
    storageBucket: 'ai-chat-bot-d574b.firebasestorage.app',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRZxwOzpmKx54FxdQBFgobymytAUXmzjA',
    appId: '1:961015937007:ios:69c50ff7e7152b9a21e81a',
    messagingSenderId: '961015937007',
    projectId: 'ai-chat-bot-d574b',
    storageBucket: 'ai-chat-bot-d574b.firebasestorage.app',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDND25OUD0xZ0Vfhxad2m1LH0h8bUvlug',
    appId: '1:961015937007:web:3a5a49982c0c169121e81a',
    messagingSenderId: '961015937007',
    projectId: 'ai-chat-bot-d574b',
    authDomain: 'ai-chat-bot-d574b.firebaseapp.com',
    storageBucket: 'ai-chat-bot-d574b.firebasestorage.app',
    measurementId: 'G-0PYW2T2EHS',
  );
}
